

name: TDSA
# jobs
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

# installing dependencies
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"

# install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip


# Access SSH Key
    - name: Add ssh-agent to clone private repo
      uses: webfactory/ssh-agent@v0.4.1 
      with:          
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


# install requirements.txt
    - name: Install Requirements.txt
      run:
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


# Credentials for terraform access
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: eu-west-2


# run build.sh
    - name: Run build.sh
      run: |
        sh build.sh
       

# Terraform
    - name: Deploy terraform resources
      run: |
        cd terraform
        terraform init
        terraform destroy --auto-approve
